version: '3.6'

services:
  customer-service: #Web app docker container
    build: .
    hostname: customer-service
    ports:
      - "7001:7001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql_server:
        condition: service_healthy


  phpmyadmin3: #PHPmyAdmin docker container
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin3
    links:
      - mysql_server
    restart: always
    ports:
      - 5014:80
    environment:
      - PMA_ARBITRARY=1



  mysql_server: #MySQL DB docker container
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customer-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-psecretpwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
